title: "Weakly Supervised Monocular 3D Detection with a Single-View Image"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Jiang_Weakly_Supervised_Monocular_3D_Detection_with_a_Single-View_Image_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
