title: "DeiT-LT: Distillation Strikes Back for Vision Transformer Training on Long-Tailed Datasets"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Rangwani_DeiT-LT_Distillation_Strikes_Back_for_Vision_Transformer_Training_on_Long-Tailed_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
