title: "SelfPose3d: Self-Supervised Multi-Person Multi-View 3d Pose Estimation"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Srivastav_SelfPose3d_Self-Supervised_Multi-Person_Multi-View_3d_Pose_Estimation_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
