title: "Part-aware Unified Representation of Language and Skeleton for Zero-shot Action Recognition"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Zhu_Part-aware_Unified_Representation_of_Language_and_Skeleton_for_Zero-shot_Action_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
title_zh: NOT_SPECIFIED
field_zh: null
task_zh: null
summary_one_line_zh: NOT_SPECIFIED
