title: "Pose-Guided Self-Training with Two-Stage Clustering for Unsupervised Landmark Discovery"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Tourani_Pose-Guided_Self-Training_with_Two-Stage_Clustering_for_Unsupervised_Landmark_Discovery_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
