title: "OmniSDF: Scene Reconstruction using Omnidirectional Signed Distance Functions and Adaptive Binoctrees"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Kim_OmniSDF_Scene_Reconstruction_using_Omnidirectional_Signed_Distance_Functions_and_Adaptive_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
title_zh: NOT_SPECIFIED
field_zh: null
task_zh: null
summary_one_line_zh: NOT_SPECIFIED
