title: "Communication-Efficient Collaborative Perception via Information Filling with Codebook"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Hu_Communication-Efficient_Collaborative_Perception_via_Information_Filling_with_Codebook_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
title_zh: NOT_SPECIFIED
field_zh: null
task_zh: null
summary_one_line_zh: NOT_SPECIFIED
