title: "VOODOO 3D: Volumetric Portrait Disentanglement For One-Shot 3D Head Reenactment"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Tran_VOODOO_3D_Volumetric_Portrait_Disentanglement_For_One-Shot_3D_Head_Reenactment_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
