title: "From Activation to Initialization: Scaling Insights for Optimizing Neural Fields"
authors: []
venue: "CVPR"
year: 2024
url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Saratchandran_From_Activation_to_Initialization_Scaling_Insights_for_Optimizing_Neural_Fields_CVPR_2024_paper.pdf"
code_url: null
field: null
task: null
summary_one_line: NOT_SPECIFIED
